// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhkzrrxbrsvzgcufcykl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoa3pycnhicnN2emdjdWZjeWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDEyODYsImV4cCI6MjA3NDQ3NzI4Nn0.6pnlhwXOQHQNZu_KszA8rFpkfI8sKtkeBsHCepx7ANI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});