import { create } from 'zustand';

interface LanguageState {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
}

export const useLanguage = create<LanguageState>((set) => ({
  language: 'ar',
  setLanguage: (lang) => {
    // Update localStorage
    localStorage.setItem('language', lang);
    
    // Update document attributes for RTL support
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    // Add/remove RTL class for styling
    if (lang === 'ar') {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
    
    set({ language: lang });
  },
}));

export const translations = {
  en: {
    // Common
    welcomeBack: 'Welcome back!',
    status: 'Status',
    active: 'Active',
    edit: 'Edit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    loading: 'Loading...',
    
    // Dashboard
    overview: 'Overview',
    orders: 'Orders',
    menu: 'Menu',
    profile: 'Profile',
    reports: 'Reports',
    analytics: 'Analytics',
    settings: 'Settings',
    logout: 'Logout',
    
    // Stats
    totalOrders: 'Total Orders',
    revenue: 'Revenue',
    menuItems: 'Menu Items',
    rating: 'Rating',
    thisMonth: 'This month',
    activeProducts: 'Active products',
    averageRating: 'Average rating',
    
    // Quick Actions
    businessProfile: 'Business Profile',
    manageProfile: 'Manage Profile',
    manageBusinessInfo: 'Manage your business information and settings',
    menuManagement: 'Menu Management',
    manageMenu: 'Manage Menu',
    addManageFoodItems: 'Add and manage your food items and prices',
    orderManagement: 'Order Management',
    viewOrders: 'View Orders',
    receiveManageOrders: 'Receive and manage customer orders',
    
    // Profile
    editProfile: 'Edit Profile',
    businessOverview: 'Business Overview',
    verified: 'Verified',
    featured: 'Featured',
    contactInformation: 'Contact Information',
    location: 'Location',
    operatingHours: 'Operating Hours',
    deliveryInformation: 'Delivery Information',
    minimumOrder: 'Minimum Order',
    deliveryFee: 'Delivery Fee',
    deliveryTime: 'Delivery Time',
    visitWebsite: 'Visit Website',
    deliversWithin: 'Delivers within',
    closed: 'Closed',
    
    // Menu/Products
    productManagement: 'Product Management',
    manageMenuItems: 'Manage your menu items and products',
    addProduct: 'Add Product',
    searchProducts: 'Search products...',
    allCategories: 'All Categories',
    allProducts: 'All Products',
    availableOnly: 'Available Only',
    unavailableOnly: 'Unavailable Only',
    total: 'Total',
    available: 'Available',
    unavailable: 'Unavailable',
    noProductsYet: 'No Products Yet',
    startBuildingMenu: 'Start building your menu by adding your first product',
    addYourFirstProduct: 'Add Your First Product',
    noProductsFound: 'No Products Found',
    tryAdjustingFilters: 'Try adjusting your search or filter criteria',
    
    // Product Form
    editProduct: 'Edit Product',
    addNewProduct: 'Add New Product',
    productNameEn: 'Product Name (English)',
    productNameAr: 'Product Name (Arabic)',
    descriptionEn: 'Description (English)',
    descriptionAr: 'Description (Arabic)',
    productImage: 'Product Image',
    price: 'Price',
    category: 'Category',
    noCategory: 'No Category',
    prepTime: 'Prep Time (minutes)',
    availableForOrders: 'Available for Orders',
    customersCanOrder: 'Customers can order this product when available',
    updateProduct: 'Update Product',
    saving: 'Saving...',
    min: 'min',
    
    // Registration
    customerRegistration: 'Customer Registration',
    createAccount: 'Create Your Account',
    joinTalabat: 'Join Talabat Rwanda',
    fullName: 'Full Name',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    phone: 'Phone Number',
    register: 'Register',
    registering: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    
    // Validation
    fullNameRequired: 'Full name is required',
    emailRequired: 'Email is required',
    invalidEmail: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    confirmPasswordRequired: 'Please confirm your password',
    passwordsDontMatch: "Passwords don't match",
    phoneRequired: 'Phone number is required',
    phoneMinLength: 'Please enter a valid phone number',
    
    // Success
    accountCreated: 'Account Created!',
    checkEmail: 'Please check your email for verification',
    
    // Dashboard
    customerDashboard: 'Customer Dashboard',
    dashboardComingSoon: 'Customer Dashboard Coming Soon',
    
    // Email verification
    emailVerification: 'Email Verification',
    verifyYourEmail: 'Verify Your Email',
    verificationSent: 'Verification link sent to your email',
    checkInbox: 'Please check your inbox and click the verification link',
    resendVerification: 'Resend Verification',
    
    // Landing page
    popularCategories: 'Popular Categories',
    discoverCuisines: 'Discover delicious dishes from various cuisines',
    deliverTo: 'Deliver to:',
    searchPlaceholder: 'Search for market products or stores',
    
    // Language
    language: 'Language',
    
    // Supplier Registration
    supplierRegistration: 'Supplier Registration',
    joinAsPartner: 'Join as Restaurant Partner',
    accountDetails: 'Account Details',
    businessInformation: 'Business Information',
    operatingDetails: 'Operating Details',
    businessName: 'Business Name',
    businessNameEn: 'Business Name (English)',
    businessNameAr: 'Business Name (Arabic)',
    businessType: 'Business Type',
    restaurant: 'Restaurant',
    cafe: 'Café',
    fastFood: 'Fast Food',
    bakery: 'Bakery',
    other: 'Other',
    description: 'Description',
    address: 'Address',
    whatsappNumber: 'WhatsApp Number',
    openingTime: 'Opening Time',
    closingTime: 'Closing Time',
    serviceArea: 'Service Areas',
    serviceAreaPlaceholder: 'Enter area name and press Enter',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit Application',
    submitting: 'Submitting...',
    step: 'Step',
    of: 'of',
    
    // Pending approval
    registrationPending: 'Registration Pending',
    applicationSubmitted: 'Application Submitted Successfully!',
    pendingReview: 'Your application is under review',
    approvalProcess: 'Our team will review your application within 2-3 business days',
    contactInfo: 'We will contact you via email and WhatsApp once approved',
    backToHome: 'Back to Home',
    
    // Reports & Analytics
    reportsAnalytics: 'Reports & Analytics',
    reportsDescription: 'Generate detailed business reports and insights',
    totalReports: 'Total Reports',
    avgGeneration: 'Avg Generation',
    lastGenerated: 'Last Generated',
    generateReports: 'Generate Reports',
    recentReports: 'Recent Reports',
    scheduledReports: 'Scheduled Reports',
    filter: 'Filter',
    schedule: 'Schedule',
    trackPerformance: 'Track your business performance',
    
    // Analytics
    totalRevenue: 'Total Revenue',
    uniqueCustomers: 'Unique Customers',
    vsLastPeriod: 'vs last period',
    ordersByTime: 'Orders by Time',
    peakHoursAnalysis: 'Peak hours analysis',
    performanceIndicators: 'Performance Indicators',
    keyBusinessMetrics: 'Key business metrics',
    orderFulfillmentRate: 'Order Fulfillment Rate',
    averagePrepTime: 'Average Prep Time',
    customerSatisfaction: 'Customer Satisfaction',
    repeatCustomerRate: 'Repeat Customer Rate',
    topPerformingProducts: 'Top Performing Products',
    bestSellingItems: 'Your best-selling items this period',
    bestSeller: 'Best Seller',
    customerInsights: 'Customer Insights',
    understandingCustomers: 'Understanding your customer base',
    newCustomers: 'New Customers',
    returningCustomers: 'Returning Customers',
    averageOrderValue: 'Average Order Value',
    customerLifetimeValue: 'Customer Lifetime Value',
    customerFeedback: 'Customer Feedback',
    recentReviews: 'Recent reviews and ratings',
    goalsTargets: 'Goals & Targets',
    trackObjectives: 'Track your business objectives',
    monthlyRevenueGoal: 'Monthly Revenue Goal',
    orderVolumeTarget: 'Order Volume Target',
    customerRatingGoal: 'Customer Rating Goal',
    operationalMetrics: 'Operational Metrics',
    restaurantEfficiency: 'Restaurant efficiency',
    orderAccuracy: 'Order Accuracy',
    onTimeDelivery: 'On-Time Delivery',
    cancelledOrders: 'Cancelled Orders',
    growthMetrics: 'Growth Metrics',
    businessGrowthTrends: 'Business growth trends',
    revenueGrowth: 'Revenue Growth',
    customerGrowth: 'Customer Growth',
    orderGrowth: 'Order Growth',
    marketShare: 'Market Share',
    
    // Order Management
    filters: 'Filters',
    searchOrders: 'Search Orders',
    searchPlaceholderOrders: 'Search by order number, customer name, or phone...',
    filterByStatus: 'Filter by Status',
    allStatuses: 'All Statuses',
    all: 'All',
    pending: 'Pending',
    confirmed: 'Confirmed',
    preparing: 'Preparing',
    ready: 'Ready',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    noOrdersFound: 'No orders found',
    noOrdersMatch: 'No orders match your current filters',
    noOrdersYet: "You don't have any orders yet",
    viewDetails: 'View Details',
    items: 'items',
    
    // Error Messages
    error: 'Error',
    errorOccurred: 'An error occurred',
    tryAgain: 'Try Again',
    somethingWentWrong: 'Something went wrong',
    couldNotLoad: 'Could not load data',
    couldNotSave: 'Could not save changes',
    
    // Navigation
    home: 'Home',
    search: 'Search',
    cart: 'Cart',
    favorites: 'Favorites',
    account: 'Account',
    
    // Supplier Profile
    deliverySettings: 'Delivery Settings',
    deliveryRadius: 'Delivery Radius (km)',
    minDeliveryTime: 'Min Delivery Time (minutes)',
    maxDeliveryTime: 'Max Delivery Time (minutes)',
    minimumOrderAmount: 'Minimum Order Amount (RWF)',
    updateProfile: 'Update Profile',
    businessImages: 'Business Images',
    logoImage: 'Logo Image',
    coverImage: 'Cover Image',
    uploadImage: 'Upload Image',
    removeImage: 'Remove Image',
    
    // Days of week
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    suppliers: 'Suppliers',
    customers: 'Customers',
    categories: 'Categories',
    manageSuppliers: 'Manage Suppliers',
    approveSupplier: 'Approve Supplier',
    rejectSupplier: 'Reject Supplier',
    inactive: 'Inactive',
    adminPanel: 'Admin Panel',
    systemAdministrator: 'System Administrator',
    adminSettings: 'Admin Settings',
    systemSettings: 'System Settings',
    dashboard: 'Dashboard',
    users: 'Users',
    slideshow: 'Slideshow',
    featuredRestaurants: 'Featured Restaurants',
    managePerformance: 'Manage suppliers, monitor performance, and oversee operations',
    totalSuppliers: 'Total Suppliers',
    pendingApprovals: 'Pending Approvals',
    activeSuppliers: 'Active Suppliers',
    totalCustomers: 'Total Customers',
    fromLastMonth: 'from last month',
    pendingApproval: 'Pending Approval',
    allSuppliers: 'All Suppliers',
    suppliersAwaitingApproval: 'Suppliers Awaiting Approval',
    reviewApproveSuppliers: 'Review and approve new supplier applications',
    allCaughtUp: 'All caught up!',
    noPendingSuppliers: 'No suppliers pending approval at the moment.',
    activeSuppliersList: 'Active Suppliers',
    currentlyApprovedSuppliers: 'Currently approved and active suppliers',
    allSuppliersList: 'All Suppliers',
    completeSupplierList: 'Complete list of all registered suppliers',
    approve: 'Approve',
    reject: 'Reject',
    manage: 'Manage',
    appliedOn: 'Applied',
    activeSince: 'Active since',
    pendingReviewStatus: 'Pending Review',
  },
  ar: {
    // Common
    welcomeBack: 'مرحباً بعودتك!',
    status: 'الحالة',
    active: 'نشط',
    edit: 'تعديل',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    loading: 'جاري التحميل...',
    
    // Dashboard
    overview: 'نظرة عامة',
    orders: 'الطلبات',
    menu: 'القائمة',
    profile: 'الملف الشخصي',
    reports: 'التقارير',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    
    // Stats
    totalOrders: 'إجمالي الطلبات',
    revenue: 'الإيرادات',
    menuItems: 'عناصر القائمة',
    rating: 'التقييم',
    thisMonth: 'هذا الشهر',
    activeProducts: 'المنتجات النشطة',
    averageRating: 'متوسط التقييم',
    
    // Quick Actions
    businessProfile: 'ملف العمل',
    manageProfile: 'إدارة الملف',
    manageBusinessInfo: 'إدارة معلومات عملك والإعدادات',
    menuManagement: 'إدارة القائمة',
    manageMenu: 'إدارة القائمة',
    addManageFoodItems: 'إضافة وإدارة عناصر الطعام والأسعار',
    orderManagement: 'إدارة الطلبات',
    viewOrders: 'عرض الطلبات',
    receiveManageOrders: 'استلام وإدارة طلبات العملاء',
    
    // Profile
    editProfile: 'تعديل الملف',
    businessOverview: 'نظرة عامة على العمل',
    verified: 'موثق',
    featured: 'مميز',
    contactInformation: 'معلومات الاتصال',
    location: 'الموقع',
    operatingHours: 'ساعات العمل',
    deliveryInformation: 'معلومات التوصيل',
    minimumOrder: 'الحد الأدنى للطلب',
    deliveryFee: 'رسوم التوصيل',
    deliveryTime: 'وقت التوصيل',
    visitWebsite: 'زيارة الموقع',
    deliversWithin: 'التوصيل ضمن',
    closed: 'مغلق',
    
    // Menu/Products
    productManagement: 'إدارة المنتجات',
    manageMenuItems: 'إدارة عناصر القائمة والمنتجات',
    addProduct: 'إضافة منتج',
    searchProducts: 'البحث عن المنتجات...',
    allCategories: 'جميع الفئات',
    allProducts: 'جميع المنتجات',
    availableOnly: 'متوفر فقط',
    unavailableOnly: 'غير متوفر فقط',
    total: 'الإجمالي',
    available: 'متوفر',
    unavailable: 'غير متوفر',
    noProductsYet: 'لا توجد منتجات بعد',
    startBuildingMenu: 'ابدأ في بناء قائمتك عن طريق إضافة منتجك الأول',
    addYourFirstProduct: 'أضف منتجك الأول',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryAdjustingFilters: 'حاول تعديل معايير البحث أو الفلتر',
    
    // Product Form
    editProduct: 'تعديل المنتج',
    addNewProduct: 'إضافة منتج جديد',
    productNameEn: 'اسم المنتج (بالإنجليزية)',
    productNameAr: 'اسم المنتج (بالعربية)',
    descriptionEn: 'الوصف (بالإنجليزية)',
    descriptionAr: 'الوصف (بالعربية)',
    productImage: 'صورة المنتج',
    price: 'السعر',
    category: 'الفئة',
    noCategory: 'بدون فئة',
    prepTime: 'وقت التحضير (بالدقائق)',
    availableForOrders: 'متاح للطلب',
    customersCanOrder: 'يمكن للعملاء طلب هذا المنتج عندما يكون متاحاً',
    updateProduct: 'تحديث المنتج',
    saving: 'جاري الحفظ...',
    min: 'دقيقة',
    
    // Registration
    customerRegistration: 'تسجيل العملاء',
    createAccount: 'إنشاء حسابك',
    joinTalabat: 'انضم إلى طلبات رواندا',
    fullName: 'الاسم الكامل',
    email: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    phone: 'رقم الهاتف',
    register: 'تسجيل',
    registering: 'إنشاء الحساب...',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    signIn: 'تسجيل الدخول',
    
    // Validation
    fullNameRequired: 'الاسم الكامل مطلوب',
    emailRequired: 'البريد الإلكتروني مطلوب',
    invalidEmail: 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    passwordRequired: 'كلمة المرور مطلوبة',
    passwordMinLength: 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    confirmPasswordRequired: 'يرجى تأكيد كلمة المرور',
    passwordsDontMatch: 'كلمات المرور غير متطابقة',
    phoneRequired: 'رقم الهاتف مطلوب',
    phoneMinLength: 'يرجى إدخال رقم هاتف صحيح',
    
    // Success
    accountCreated: 'تم إنشاء الحساب!',
    checkEmail: 'يرجى التحقق من بريدك الإلكتروني للتحقق',
    
    // Dashboard
    customerDashboard: 'لوحة تحكم العميل',
    dashboardComingSoon: 'لوحة تحكم العميل قريباً',
    
    // Email verification
    emailVerification: 'التحقق من البريد الإلكتروني',
    verifyYourEmail: 'تحقق من بريدك الإلكتروني',
    verificationSent: 'تم إرسال رابط التحقق إلى بريدك الإلكتروني',
    checkInbox: 'يرجى التحقق من صندوق الوارد والنقر على رابط التحقق',
    resendVerification: 'إعادة إرسال التحقق',
    
    // Landing page
    popularCategories: 'الفئات الشائعة',
    discoverCuisines: 'اكتشف أطباق لذيذة من مختلف المأكولات',
    deliverTo: 'التوصيل إلى:',
    searchPlaceholder: 'ابحث عن منتجات السوق أو المتاجر',
    
    // Language
    language: 'اللغة',
    
    // Supplier Registration
    supplierRegistration: 'تسجيل المورد',
    joinAsPartner: 'انضم كشريك مطعم',
    accountDetails: 'تفاصيل الحساب',
    businessInformation: 'معلومات العمل',
    operatingDetails: 'تفاصيل التشغيل',
    businessName: 'اسم العمل',
    businessNameEn: 'اسم العمل (بالإنجليزية)',
    businessNameAr: 'اسم العمل (بالعربية)',
    businessType: 'نوع العمل',
    restaurant: 'مطعم',
    cafe: 'مقهى',
    fastFood: 'وجبات سريعة',
    bakery: 'مخبز',
    other: 'أخرى',
    description: 'الوصف',
    address: 'العنوان',
    whatsappNumber: 'رقم الواتساب',
    openingTime: 'وقت الافتتاح',
    closingTime: 'وقت الإغلاق',
    serviceArea: 'مناطق الخدمة',
    serviceAreaPlaceholder: 'أدخل اسم المنطقة واضغط Enter',
    next: 'التالي',
    previous: 'السابق',
    submit: 'تقديم الطلب',
    submitting: 'جاري التقديم...',
    step: 'خطوة',
    of: 'من',
    
    // Pending approval
    registrationPending: 'التسجيل معلق',
    applicationSubmitted: 'تم تقديم الطلب بنجاح!',
    pendingReview: 'طلبك قيد المراجعة',
    approvalProcess: 'سيراجع فريقنا طلبك خلال 2-3 أيام عمل',
    contactInfo: 'سنتواصل معك عبر البريد الإلكتروني والواتساب بمجرد الموافقة',
    backToHome: 'العودة للرئيسية',
    
    // Reports & Analytics
    reportsAnalytics: 'التقارير والتحليلات',
    reportsDescription: 'إنشاء تقارير تفصيلية ورؤى الأعمال',
    totalReports: 'إجمالي التقارير',
    avgGeneration: 'متوسط التوليد',
    lastGenerated: 'آخر إنشاء',
    generateReports: 'إنشاء التقارير',
    recentReports: 'التقارير الأخيرة',
    scheduledReports: 'التقارير المجدولة',
    filter: 'تصفية',
    schedule: 'جدولة',
    trackPerformance: 'تتبع أداء عملك',
    
    // Analytics
    totalRevenue: 'إجمالي الإيرادات',
    uniqueCustomers: 'العملاء الفريدون',
    vsLastPeriod: 'مقارنة بالفترة السابقة',
    ordersByTime: 'الطلبات حسب الوقت',
    peakHoursAnalysis: 'تحليل ساعات الذروة',
    performanceIndicators: 'مؤشرات الأداء',
    keyBusinessMetrics: 'مقاييس الأعمال الرئيسية',
    orderFulfillmentRate: 'معدل تنفيذ الطلبات',
    averagePrepTime: 'متوسط وقت التحضير',
    customerSatisfaction: 'رضا العملاء',
    repeatCustomerRate: 'معدل العملاء المتكررين',
    topPerformingProducts: 'المنتجات الأكثر أداءً',
    bestSellingItems: 'العناصر الأكثر مبيعاً في هذه الفترة',
    bestSeller: 'الأكثر مبيعاً',
    customerInsights: 'رؤى العملاء',
    understandingCustomers: 'فهم قاعدة عملائك',
    newCustomers: 'عملاء جدد',
    returningCustomers: 'عملاء متكررون',
    averageOrderValue: 'متوسط قيمة الطلب',
    customerLifetimeValue: 'القيمة الدائمة للعميل',
    customerFeedback: 'تعليقات العملاء',
    recentReviews: 'المراجعات والتقييمات الأخيرة',
    goalsTargets: 'الأهداف والغايات',
    trackObjectives: 'تتبع أهداف عملك',
    monthlyRevenueGoal: 'هدف الإيرادات الشهرية',
    orderVolumeTarget: 'هدف حجم الطلبات',
    customerRatingGoal: 'هدف تقييم العملاء',
    operationalMetrics: 'مقاييس التشغيل',
    restaurantEfficiency: 'كفاءة المطعم',
    orderAccuracy: 'دقة الطلب',
    onTimeDelivery: 'التوصيل في الوقت المحدد',
    cancelledOrders: 'الطلبات الملغاة',
    growthMetrics: 'مقاييس النمو',
    businessGrowthTrends: 'اتجاهات نمو الأعمال',
    revenueGrowth: 'نمو الإيرادات',
    customerGrowth: 'نمو العملاء',
    orderGrowth: 'نمو الطلبات',
    marketShare: 'حصة السوق',
    
    // Order Management
    filters: 'التصفيات',
    searchOrders: 'بحث الطلبات',
    searchPlaceholderOrders: 'البحث برقم الطلب أو اسم العميل أو الهاتف...',
    filterByStatus: 'تصفية حسب الحالة',
    allStatuses: 'جميع الحالات',
    all: 'الكل',
    pending: 'قيد الانتظار',
    confirmed: 'مؤكد',
    preparing: 'قيد التحضير',
    ready: 'جاهز',
    delivered: 'تم التوصيل',
    cancelled: 'ملغى',
    noOrdersFound: 'لم يتم العثور على طلبات',
    noOrdersMatch: 'لا توجد طلبات تطابق التصفيات الحالية',
    noOrdersYet: 'ليس لديك أي طلبات حتى الآن',
    viewDetails: 'عرض التفاصيل',
    items: 'عناصر',
    
    // Error Messages
    error: 'خطأ',
    errorOccurred: 'حدث خطأ',
    tryAgain: 'حاول مرة أخرى',
    somethingWentWrong: 'حدث خطأ ما',
    couldNotLoad: 'تعذر تحميل البيانات',
    couldNotSave: 'تعذر حفظ التغييرات',
    
    // Navigation
    home: 'الرئيسية',
    search: 'البحث',
    cart: 'السلة',
    favorites: 'المفضلة',
    account: 'الحساب',
    
    // Supplier Profile
    deliverySettings: 'إعدادات التوصيل',
    deliveryRadius: 'نطاق التوصيل (كم)',
    minDeliveryTime: 'الحد الأدنى لوقت التوصيل (دقائق)',
    maxDeliveryTime: 'الحد الأقصى لوقت التوصيل (دقائق)',
    minimumOrderAmount: 'الحد الأدنى لمبلغ الطلب (فرنك رواندي)',
    updateProfile: 'تحديث الملف',
    businessImages: 'صور العمل',
    logoImage: 'صورة الشعار',
    coverImage: 'صورة الغلاف',
    uploadImage: 'تحميل صورة',
    removeImage: 'إزالة الصورة',
    
    // Days of week
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    sunday: 'الأحد',
    
    // Admin
    adminDashboard: 'لوحة تحكم المدير',
    suppliers: 'الموردين',
    customers: 'العملاء',
    categories: 'الفئات',
    manageSuppliers: 'إدارة الموردين',
    approveSupplier: 'الموافقة على المورد',
    rejectSupplier: 'رفض المورد',
    inactive: 'غير نشط',
    adminPanel: 'لوحة الإدارة',
    systemAdministrator: 'مدير النظام',
    adminSettings: 'إعدادات الإدارة',
    systemSettings: 'إعدادات النظام',
    dashboard: 'لوحة التحكم',
    users: 'المستخدمين',
    slideshow: 'عرض الشرائح',
    featuredRestaurants: 'المطاعم المميزة',
    managePerformance: 'إدارة الموردين ومراقبة الأداء والإشراف على العمليات',
    totalSuppliers: 'إجمالي الموردين',
    pendingApprovals: 'الموافقات المعلقة',
    activeSuppliers: 'الموردين النشطين',
    totalCustomers: 'إجمالي العملاء',
    fromLastMonth: 'من الشهر الماضي',
    pendingApproval: 'الموافقة المعلقة',
    allSuppliers: 'جميع الموردين',
    suppliersAwaitingApproval: 'الموردين في انتظار الموافقة',
    reviewApproveSuppliers: 'مراجعة والموافقة على طلبات الموردين الجدد',
    allCaughtUp: 'كل شيء محدث!',
    noPendingSuppliers: 'لا يوجد موردين في انتظار الموافقة في الوقت الحالي.',
    activeSuppliersList: 'الموردين النشطين',
    currentlyApprovedSuppliers: 'الموردين المعتمدين والنشطين حالياً',
    allSuppliersList: 'جميع الموردين',
    completeSupplierList: 'قائمة كاملة بجميع الموردين المسجلين',
    approve: 'موافقة',
    reject: 'رفض',
    manage: 'إدارة',
    appliedOn: 'تقدم في',
    activeSince: 'نشط منذ',
    pendingReviewStatus: 'قيد المراجعة',
  },
} as const;
